### PR TITLE
packages with the searched name are definitely at the top now

### LINKED ISSUE #1029: exact match not listed on first page of search results
A keyword search such as https://www.npmjs.com/search?q=stylus does not list the exact match "stylus" package on the first page of results. It's on page 5. I'm pretty sure this is a regression as I recall this working in the past.

### PR DESCRIPTION
**Pull request by rockbot**
fixes #1029 and #1066 

when we updated search we forgot to push the exact-name matches to the top. this is now fixed :-)

### CODE REVIEW

**Comment by feross** [comment]
NICE!

**Comment by jden** [comment]
:+1:

**Comment by noopkat** [comment]
🎉❤️

**Comment by feross** [comment]
Another improvement would be to demote deprecated packages.
https://staging.npmjs.com/search?q=webtorrent shows "webtorrent-tracker"
and "webtorrent-swarm" which are both deprecated now.

File: facets/registry/show-search.js [hunk 1]
```diff
@@ -22,22 +22,41 @@ module.exports = function (request, reply) {
...
-                    boost: 20
+        "dis_max": {
+          "tie_breaker": 0.9,
+          "boost": 1.2,
+          "queries": [
+            {
+              "function_score": {
+                "query": {
+                  "match": {
+                    "name.untouched": request.query.q
```
Comment (ceejbot) [inline facets/registry/show-search.js]: Boommity boom. The thing I like: that this is the only tinkering with the result scores.

**Comment by jefflembeck** [comment]
results for grunt-grunticon 2015-07-20 08-37-06

So, interesting thing, searching for something that has packages with same term, but with a hyphenated suffix, seems to yield interesting results

**Comment by jefflembeck** [comment]
:sheep:

**Comment by jefflembeck** [comment]
yay
